services:
  cdd-under-construction:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cdd-under-construction
    ports:
      - "4004:80"
      - "4005:81"
    restart: unless-stopped
    networks:
      - cdd-network

networks:
  cdd-network:
    name: cdd-network
    external: true
